Surprisingly the only VS 2017 issue with aom
VS 2017 does not like constexprs. I thought they had fixed it in later releases since JXL used to not compile, but then Microsoft fixed the issue and JXL compiles with it, but I guess they never fixed whatever this does.

```
"C:\Projects\aom_build\AOM.sln" (default target) (1) ->
"C:\Projects\aom_build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"C:\Projects\aom_build\test_aom_encoder.vcxproj.metaproj" (default target) (144) ->
"C:\Projects\aom_build\test_aom_encoder.vcxproj" (default target) (145) ->
(ClCompile target) ->
  C:\Projects\aom\test\encode_small_width_height_test.cc(28): error C2131: expression did not evaluate to a constant [C:\Projects\aom_build\test_aom_encoder.vcxproj]

    397 Warning(s)
    1 Error(s)
```

AI suggested fix, which just seperates out the calculation I think idk I'm not smart.
I was also suggested two other replacements which compile fine, but since this ones keeps the main constexpr I'll use this one. If you're smarter than me and think one of these looks better, let me know. Although it's just a test so idk if it that big of a deal.

```
enum { kBufferSize = 2 * (256 * 512 + 2 * 128 * 256) };
static const unsigned char kBuffer[kBufferSize] = { 0 };
```

```
static const unsigned char kBuffer[2 * (256 * 512 + 2 * 128 * 256)] = { 0 };
```